contatos/urls.py
from django.urls import path
from contatos.views import view_contatos, create_contact

app_name = 'contatos'

urlpatterns = [
    path('', view_contatos, name='url_contatos'),
    path('create_contact/', create_contact, name='create_contact'),
]

malves/base/urls.py
from django.urls import path
from malves.base.views import home


app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

malves/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    # views de postagens
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:postagem>/', views.post_detail, name='post_detail'),
]

malves/dashboard/urls.py
from django.urls import path
from .views import dashboard

app_name = 'dashboard'

urlpatterns = [
    path('', dashboard, name='dashboard')
]

malves/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('conta/', include('django.contrib.auth.urls')),
    path('', include('malves.base.urls')),
    path('servicos/', include('malves.servicos.urls')),
    path('contatos/', include('malves.contatos.urls')),
    path('noticias/', include('malves.blog.urls', namespace='blog')),
    path('dashboard/', include('malves.dashboard.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

handler404 = 'malves.base.views.handler404'
handler500 = 'malves.base.views.handler500'

servicos/urls.py
from django.urls import path
from servicos.views import view_servicos


app_name = 'servicos'

urlpatterns = [
    path('', view_servicos, name='view_servicos'),
]

malves/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.
    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

malves/base/views.py
from django.shortcuts import render
from django.http import HttpResponse # noqa
from malves.blog.views import Postagem
# Create your views here.


def home(request):
    latest_postagens = Postagem.published.order_by('-publicar')[:2]
    context = {'latest_postagens': latest_postagens, 'section': 'home'}
    return render(request, 'base/home.html', context)


def handler404(request, exception):
    context = {}
    response = render(request, 'base/error-404.html', context=context)
    response.status_code = 404
    return response


def handler500(request):
    context = {}
    response = render(request, 'base/error-500.html', context=context)
    response.status_code = 500
    return response

malves/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Autoescola Malves{% endblock title %}</title>

    <meta name="description"
          content="A Auto escola malves é um centro de formação de condutores B localizado na zona sul de São Paulo, entre em contato para ter mais informações.">
    <meta name="author" content="Helton Teixeira">

    <!-- fontawesome para usar icons-->
    <script src="https://kit.fontawesome.com/00046ce686.js" crossorigin="anonymous"></script>

    <link rel="icon" type="image/png" href="{% static 'favicon.png' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</head>
<body>


<!-- inicio navbar -->
<nav class="navbar navbar-expand-lg navbar-dark sticky-top shadow-sm  corNav">
    <a class="navbar-brand" href="{% url 'base:home' %}">AE MALVES</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
            <li {% if section == "home" %}class="selected"{% else %} class="nav-item active"{% endif %}>
			    <a class="nav-link" href="{% url 'base:home' %}">Home <span class="sr-only"></span></a>
			</li>
			<li {% if section == "servicos" %}class="selected"{% else %}class="nav-item active"{% endif %}>
			    <a class="nav-link" href="{% url 'servicos:view_servicos' %}">Serviços <span class="sr-only"></span></a>
			</li>
			<li {% if section == "contatos" %}class="selected" {% else %}class="nav-item active"{% endif %}>
			    <a class="nav-link" href="{% url 'contatos:url_contatos' %}">Contato <span class="sr-only"></span></a>
			</li>
        </ul>
        <div class="d-flex pr-5">
            <a href="https://www.instagram.com/autoescolamalves/" target="_blank"><i
                    class="icones fab fa-instagram fa-1x pr-2"></i></a>
            <a href="https://pt-br.facebook.com/AutoEscolaMalves/" target="_blank"> <i
                    class="icones fab fa-facebook-square fa-1x pr-2 "></i> </a>
            <a href="https://www.linkedin.com/company/auto-moto-escola-malves/" target="_blank"><i
                    class="icones fab fa-linkedin fa-1x"></i></a>
        </div>
    </div>
    {% if user.is_authenticated %}
        <span class="pr-4 icones">{{ user.first_name }}</span>
         <a class="btn btn-danger" href="{% url 'logout' %}" >Sair</a>


        {% else %}
        <a class="btn btn-light" href="{% url 'login' %}">Entrar</a>
        {% endif %}
</nav>

{% block breadcrumb %}
{% endblock%}
<!-- fim navbar -->

{% block body %} {% endblock body %}

<!-- FOOTER (rodapé)-->
<footer class="main-footer mt-4 pt-2 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h2>Entre em Contato</h2>
                <address>
                    Telefone: <a href="tel:+551155225108" class="text-light">(11) 5522-5108</a>
                    <br>

                    <!--<br>-->
                    <!--<a href="mailto:cfcmalves@hotmail.com" class="text-light">cfcmalves@hotmail.com</a>-->

                    Av. Carlos Lacerda nº 3025 - São Paulo - SP
                </address>
                <p>Siga-nos:
                    <a href="https://www.instagram.com/autoescolamalves/" target="_blank"><i
                            class="icones fab fa-instagram fa-1x"></i></a>
                    <a href="https://pt-br.facebook.com/AutoEscolaMalves/" target="_blank"> <i
                            class="icones fab fa-facebook-square fa-1x "></i> </a>
                    <a href="https://www.linkedin.com/company/auto-moto-escola-malves/" target="_blank"><i
                            class="icones fab fa-linkedin fa-1x"></i></a>
                </p>
            </div>
        </div>
    </div>
    <div class="rights pb-2">
        <div class="container">
            <div class="row">
                <div class="col">
                    &copy; {% now 'Y' %} Autoescola Malves &middot; Todos os direitos reservados &middot; <a
                        href="https://heltonteixeira92.github.io/" class="text-light" target="_blank">Helton
                    Teixeira</a>
                </div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

malves/base/templates/base/error-404.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AE Malves Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'dashboard/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'dashboard/assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'dashboard/assets/images/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-primary">
          <div class="row flex-grow">
            <div class="col-lg-7 mx-auto text-white">
              <div class="row align-items-center d-flex flex-row">
                <div class="col-lg-6 text-lg-right pr-lg-4">
                  <h1 class="display-1 mb-0">404</h1>
                </div>
                <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                  <h2>SORRY!</h2>
                  <h3 class="font-weight-light">Deu ruim! página não encontrada.</h3>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 text-center mt-xl-2">
                  <a class="text-white font-weight-medium" href="{% url 'dashboard:dashboard' %}">Back to home</a>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 mt-xl-2">
                  <p class="text-white font-weight-medium text-center">Copyright &copy; 2022 All rights reserved.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'dashboard/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'dashboard/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/misc.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/settings.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/todolist.js' %}"></script>
    <!-- endinject -->
  </body>
</html>

malves/base/templates/base/error-500.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>AE Malves Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'dashboard/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'dashboard/assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'dashboard/assets/images/favicon.png' %}" />
  </head>
  <body>
    <div class="container-scroller">
      <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center text-center error-page bg-info">
          <div class="row flex-grow">
            <div class="col-lg-7 mx-auto text-white">
              <div class="row align-items-center d-flex flex-row">
                <div class="col-lg-6 text-lg-right pr-lg-4">
                  <h1 class="display-1 mb-0">500</h1>
                </div>
                <div class="col-lg-6 error-page-divider text-lg-left pl-lg-4">
                  <h2>SORRY!</h2>
                  <h3 class="font-weight-light">Internal server error!</h3>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 text-center mt-xl-2">
                  <a class="text-white font-weight-medium" href="{% url 'dashboard:dashboard' %}">Back to home</a>
                </div>
              </div>
              <div class="row mt-5">
                <div class="col-12 mt-xl-2">
                  <p class="text-white font-weight-medium text-center">Copyright &copy; 2020 All rights reserved.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- content-wrapper ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="{% static 'dashboard/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'dashboard/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/misc.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/settings.js' %}"></script>
    <script src="{% static 'dashboard/assets/js/todolist.js' %}"></script>
    <!-- endinject -->
  </body>
</html>

malves/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Ae Malves - Home{% endblock title %}


{% block body %}
<main role="main">
	<div class="container mt-3">
			<div class="row">
				<div class="col-md-12">
					<div class="carousel slide" id="carousel-998238">
						<div class="carousel-inner">
							<div class="carousel-item active">
								<img class="d-block w-100 rounded" alt="Carro Auto escola malves" src="{% static 'img/driverSchoolCar.jpeg' %}">
								<div class="carousel-caption">
									<h4 class="jumbotron-heading titulos">
										AUTO MOTO ESCOLA MALVES
									</h4>
									<p class="lead titulos">
										 VOCÊ NA DIREÇÃO CERTA!
									</p>
								</div>
							</div>
						</div>

					</div>
					<center><img src="{% static 'img/logomalves.jpeg' %}" width="250" height="250"></center>
				</div>
			</div>
			</div>

			<div class="container marketing">

			<!-- Three columns of text below the carousel -->
			<div class="row justify-content-end">
			  <div class="col-lg-3">
				<img class="bd-placeholder-img rounded-circle" src="{% static 'img/Moto.jpeg' %}" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">
				<h2>Categoria A</h2>

				  <ul><p><b>MOTO</b></p>
					 <li> Pré-cadastro</li>
					 <li> Exame médico</li>
					  <li> CFC teórico</li>
					  <li> Prova teórica</li>
					  <li> 	20 aulas práticas</li>
					  <li> 	Prova prática</li>
					  <li>  Emissão CNH</li>
				  </ul>
				<!-- <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>-->
			  </div><!-- /.col-lg-4 -->
			  <div class="col-lg-3">
				<img class="bd-placeholder-img rounded-circle" src="{% static 'img/Mobi.jpeg' %}" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">

				<h2>Categoria B</h2>

				  <ul><p><b>CARRO</b></p>
					 <li> Pré-cadastro</li>
					 <li> Exame médico</li>
					  <li> CFC teórico</li>
					  <li> Prova teórica</li>
					  <li> 	20 aulas práticas</li>
					  <li> 	Prova prática</li>
					  <li>  Emissão CNH</li>
				  </ul>
				<!--<p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>-->
			  </div>
				<!-- /.col-lg-4 -->
			  <div class="col-lg-4">
				<img class="bd-placeholder-img rounded-circle" src="{% static 'img/CarroMoto.jpeg' %}" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false">

				<h2>Categoria AB</h2>

				  <ul><p><b>CARRO E MOTO</b></p>
					 <li> Pré-cadastro</li>
					 <li> Exame médico</li>
					  <li> CFC teórico</li>
					  <li> Prova teórica</li>
					  <li> 	40 aulas práticas</li>
					  <li> 	Provas práticas</li>
					  <li>  Emissão CNH</li>
				  </ul>
				  <!-- Botão Whatsapp -->
				  <a href="https://api.whatsapp.com/send?phone=551155225108&text=Olá, Gostaria de informações"
						target="_blank"
						style="position:fixed;bottom:20px;right:30px;">
						<svg enable-background="new 0 0 512 512" width="50" height="50" version="1.1" viewBox="0 0 512 512" xml:space="preserve" xmlns="http://www.w3.org/2000/svg"><path d="M256.064,0h-0.128l0,0C114.784,0,0,114.816,0,256c0,56,18.048,107.904,48.736,150.048l-31.904,95.104  l98.4-31.456C155.712,496.512,204,512,256.064,512C397.216,512,512,397.152,512,256S397.216,0,256.064,0z" fill="#4CAF50"/><path d="m405.02 361.5c-6.176 17.44-30.688 31.904-50.24 36.128-13.376 2.848-30.848 5.12-89.664-19.264-75.232-31.168-123.68-107.62-127.46-112.58-3.616-4.96-30.4-40.48-30.4-77.216s18.656-54.624 26.176-62.304c6.176-6.304 16.384-9.184 26.176-9.184 3.168 0 6.016 0.16 8.576 0.288 7.52 0.32 11.296 0.768 16.256 12.64 6.176 14.88 21.216 51.616 23.008 55.392 1.824 3.776 3.648 8.896 1.088 13.856-2.4 5.12-4.512 7.392-8.288 11.744s-7.36 7.68-11.136 12.352c-3.456 4.064-7.36 8.416-3.008 15.936 4.352 7.36 19.392 31.904 41.536 51.616 28.576 25.44 51.744 33.568 60.032 37.024 6.176 2.56 13.536 1.952 18.048-2.848 5.728-6.176 12.8-16.416 20-26.496 5.12-7.232 11.584-8.128 18.368-5.568 6.912 2.4 43.488 20.48 51.008 24.224 7.52 3.776 12.48 5.568 14.304 8.736 1.792 3.168 1.792 18.048-4.384 35.52z" fill="#FAFAFA"/></svg>
				  </a>
			  </div><!-- /.col-lg-4 -->

			</div><!-- /.row -->
				<br>
				<center><a class="botao" href="{% url 'servicos:view_servicos' %}">Ver mais &raquo;</a></center>
				<hr class="my-4">
				<div class="container mt-5">
				<div class="row">
					<div class="col-md-12">
						<section class="container">
							<header>
								<h2>Notícias</h2>
							</header>
							<br>
							{% if latest_postagens %}
								{% for post in latest_postagens %}
									<article>
										<header>
										  <h2>
											<a class="link" href="{{ post.get_absolute_url }}"> {{ post.titulo }} </a>
										  </h2>
										  <p class="date">Publicado em <time datetime="2021-04-12T13:00:24+01:00">{{ post.criado }}</time> por <a href="#">{{ post.autor.first_name }}</a></p>
										</header>
										<p>{{ post.corpo|truncatewords:50|linebreaks }}<a href="{{ post.get_absolute_url }}" target="_parent"> ver notícia </a></p>
										<br>
									</article>
								{% endfor %}
								<center class="pb-4"><a class="botao" href="{% url 'blog:post_list' %}">Ver mais &raquo;</a></center>
							{% else %}
								<h4 class="pb-5 text-center"> ainda não temos postagens disponiveis </h4>
							{% endif %}

						</section>
							<hr class="my-3">
							<center class="float-end"><a href="#">Back to top</a></center>
							<hr class="my-3">

					</div>
				</div>
			</div>
	</div>
</main>
{% endblock body %}